### ISSUE TITLE
client id not set

### ISSUE THREAD

**Issue by mooseh** [PetterKraabol/laravel-twitch-api#1]
Although I have set the options in the twitch-api config file

im receiving resulted in a `400 Bad Request` response:
{"error":"Bad Request","status":400,"message":"No client id specified"}

**Comment by kaugesaar** [comment]
Twitch now [requires Client-ID on all requests](https://twitter.com/TwitchDev/status/776188272712245250). Even though you specify it in twitch-api config file, it's actually never used.

**Comment by mooseh** [comment]
I see so maybe a manipulation of the laravel-twitch-api is required so that it sends the set client_id

**Comment by kaugesaar** [comment]
Yeah, for now. I had to do a hot fix before I went to work. What I did was change

https://github.com/PetterKraabol/laravel-twitch-api/blob/master/src/API/Api.php#L92

``` php
$request = new Request($type, $path);
```

to

``` php
$request = new Request($type, $path, ['Client-ID' => config('twitch-api.client_id')]);
```

I'll see if I can upload a more proper fix/pull request when I get home later today.

**Comment by PetterKraabol** [comment]
Hi, yes, the client_id is unused. Send a pull request or I'll fix it when I
get home in about 10 hours.
