### ISSUE TITLE
Wrong API URL creation for subscriptions, missing slashes

### ISSUE THREAD

**Issue by evgeny-l** [PetterKraabol/laravel-twitch-api#3]
laravel-twitch-api/src/API/Subscriptions.php
Require additional slashes ('/') on line 12 and 24 around 'subscriptions'.

**Comment by PetterKraabol** [comment]
Fixed in [1.2.2](https://github.com/PetterKraabol/laravel-twitch-api/releases/tag/1.2.2). Thanks.

**Comment by evgeny-l** [comment]
Wow, quick fix. Thanks for useful packet!
