### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mooseh** [PetterKraabol/laravel-twitch-api#4]
Hi i've been using your twitch api plugin which is great but i have tried to many ways with try and catch etc etc to prevent it from bugging out should the twitch api be down but it seems to killed the site whole no matter what is there a specific way for handling errors? if not are their plans to add it?

**Comment by PetterKraabol** [comment]
I'm not that familiar with (good) error handling. Suggestions and pull requests would be awesome.

**Comment by mooseh** [comment]
So i resolved this by doing the requests via AJAX, if it files it files at least it doesn't kill the site :)

**Comment by hootener** [comment]
See PR: https://github.com/PetterKraabol/laravel-twitch-api/pull/8

It's not perfect error handling across the entire package, but checking for exceptions in `Api::sendRequest(...)` can provide better error handling for common errors that may occur when interfacing with the Twitch API. Testing shows this works to catch exceptions of both 4xx and 503 types -- which are likely the most common kinds of errors encountered with using the Twitch API.

**Comment by PetterKraabol** [comment]
Closing this due to #8.

(Pull) requests for specific error handling is welcome.
